import userRepositoryImpl from "./implementations/UserRepository.js";
import resetPasswordOTPRepositoryImpl from "./implementations/ResetPasswordOTPRepository.js";
import roomTypeRepositoryImpl from "./implementations/RoomTypeRepository.js";
import bookingRepositoryImpl from "./implementations/BookingRepository.js";
import serviceRepositoryImpl from "./implementations/ServiceRepository.js";
import roomRepositoryImpl from "./implementations/RoomRepository.js";
import customerRepositoryImpl from "./implementations/CustomerRepository.js";
import staffRepositoryImpl from "./implementations/StaffRepository.js";
import rentalReceiptRepositoryImpl from "./implementations/RentalReceiptRepository.js";
import serviceUsageRepositoryImpl from "./implementations/ServiceUsageRepository.js";

export const userRepository = userRepositoryImpl;
export const resetPasswordOTPRepository = resetPasswordOTPRepositoryImpl;
export const roomTypeRepository = roomTypeRepositoryImpl;
export const bookingRepository = bookingRepositoryImpl;
export const serviceRepository = serviceRepositoryImpl;
export const roomRepository = roomRepositoryImpl;
export const customerRepository = customerRepositoryImpl;
export const staffRepository = staffRepositoryImpl;
export const rentalReceiptRepository = rentalReceiptRepositoryImpl;
export const serviceUsageRepository = serviceUsageRepositoryImpl;
