import userRepositoryImpl from "./implementations/UserRepository.js";
import resetPasswordOTPRepositoryImpl from "./implementations/ResetPasswordOTPRepository.js";
import roomTypeRepositoryImpl from "./implementations/RoomTypeRepository.js";
import bookingRepositoryImpl from "./implementations/BookingRepository.js";
import serviceRepositoryImpl from "./implementations/ServiceRepository.js";
import roomRepositoryImpl from "./implementations/RoomRepository.js";
import customerRepositoryImpl from "./implementations/CustomerRepository.js";
import staffRepositoryImpl from "./implementations/StaffRepository.js";
import rentalReceiptRepositoryImpl from "./implementations/RentalReceiptRepository.js";
import serviceUsageRepositoryImpl from "./implementations/ServiceUsageRepository.js";
import settingsRepositoryImpl from "./implementations/SettingsRepository.js";
import paymentMethodRepositoryImpl from "./implementations/PaymentMethodRepository.js";
import invoiceRepositoryImpl from "./implementations/InvoiceRepository.js";
import bookingHistoryRepositoryImpl from "./implementations/BookingHistoryRepository.js";
import maintenanceRepositoryImpl from "./implementations/MaintenanceRepository.js";
import notificationRepositoryImpl from "./implementations/NotificationRepository.js";

export const userRepository = userRepositoryImpl;
export const resetPasswordOTPRepository = resetPasswordOTPRepositoryImpl;
export const roomTypeRepository = roomTypeRepositoryImpl;
export const bookingRepository = bookingRepositoryImpl;
export const serviceRepository = serviceRepositoryImpl;
export const roomRepository = roomRepositoryImpl;
export const customerRepository = customerRepositoryImpl;
export const staffRepository = staffRepositoryImpl;
export const rentalReceiptRepository = rentalReceiptRepositoryImpl;
export const serviceUsageRepository = serviceUsageRepositoryImpl;
export const settingsRepository = settingsRepositoryImpl;
export const paymentMethodRepository = paymentMethodRepositoryImpl;
export const invoiceRepository = invoiceRepositoryImpl;
export const bookingHistoryRepository = bookingHistoryRepositoryImpl;
export const maintenanceRepository = maintenanceRepositoryImpl;
export const notificationRepository = notificationRepositoryImpl;
